sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.11.2

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose run --service-ports pycharm python manage.py test --no-input
  - docker-compose run --service-ports pycharm behave -tags=-wip -tags=-future

after_script:
  - docker-compose down
