version: '2'



services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /daphne.sh

  nginx:
    build: ./compose/nginx
    depends_on:
      - django

    ports:
      - "0.0.0.0:80:80"


  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: celery -A nectr.taskapp worker -l INFO

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: celery -A nectr.taskapp beat -l INFO

