version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=nectr

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: "nectr"
      USE_DOCKER: "yes"
    volumes:
      - .:/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    links:
      - postgres

  hub:
    image: selenium/hub:2.52.0
    expose:
      - 4444
    ports:
      - 4444:4444

  node-firefox:
    image: selenium/node-firefox-debug:2.52.0
    depends_on:
      - hub
    ports:
      - "5900:5900"
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444

  node-chrome:
    image: selenium/node-chrome-debug:2.52.0
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444




