version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=nectr

  chromedriver:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  phantomjs:
    image: shufo/phantomjs
    command: --webdriver 8901
    ports:
      - "8901:8901"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=nectr
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - chromedriver
      - phantomjs
      - mailhog

#  pycharm:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile-dev
#    depends_on:
#      - postgres
#    environment:
#      - POSTGRES_USER=nectr
#    volumes:
#      - .:/app
#    links:
#      - postgres

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

